{% set name = "lidar" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d408e4aa6e0cd09b13813523b9ad69835ed5d61bd5f1ff27aeac1e108d34d67f

build:
  number: 0
  entry_points:
    - lidar=lidar.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=6.0
    - matplotlib-base
    - numpy
    - pysimplegui ==2.30.0
    - python >=3.7
    - richdem
    - scikit-image
    - scipy
    - gdal
    - pyshp
    - whitebox

test:
  imports:
    - lidar
  commands:
    - lidar --help

about:
  home: https://github.com/giswqs/lidar
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package for delineating nested surface depressions from digital elevation data
  doc_url: https://lidar.gishub.org
  dev_url: https://github.com/giswqs/lidar

extra:
  recipe-maintainers:
    - giswqs
