{% set name = "lidar" %}
{% set version = "0.5.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6b1103554e9e376e3107bdb9d02dacd871ac580da92b67bd186597e5700dc683

build:
  number: 0
  entry_points:
    - lidar=lidar.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - click >=6.0
    - matplotlib-base
    - numpy
    - pysimplegui ==2.30.0
    - python
    - richdem
    - scikit-image
    - scipy
    - gdal
    - pyshp
    - whitebox

test:
  imports:
    - lidar
  commands:
    - lidar --help

about:
  home: "https://github.com/giswqs/lidar"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for delineating nested surface depressions in digital elevation data"
  doc_url: https://lidar.gishub.org
  dev_url: https://github.com/giswqs/lidar

extra:
  recipe-maintainers:
    - giswqs
